/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StudentGrade = IDL.Record({
  'studentId' : IDL.Nat,
  'studentName' : IDL.Text,
  'score' : IDL.Opt(IDL.Nat),
});
export const ClassGrades = IDL.Record({
  'studentGrades' : IDL.Vec(StudentGrade),
  'average' : IDL.Opt(IDL.Nat),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const ClassInfo = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const StudentInfo = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'classId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteClass' : IDL.Func([IDL.Nat], [], []),
  'getAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassGrades' : IDL.Func([IDL.Nat], [ClassGrades], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listClasses' : IDL.Func([], [IDL.Vec(ClassInfo)], ['query']),
  'listStudents' : IDL.Func([IDL.Nat], [IDL.Vec(StudentInfo)], ['query']),
  'removeStudent' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveAttendance' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StudentGrade = IDL.Record({
    'studentId' : IDL.Nat,
    'studentName' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat),
  });
  const ClassGrades = IDL.Record({
    'studentGrades' : IDL.Vec(StudentGrade),
    'average' : IDL.Opt(IDL.Nat),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const ClassInfo = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const StudentInfo = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'classId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteClass' : IDL.Func([IDL.Nat], [], []),
    'getAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassGrades' : IDL.Func([IDL.Nat], [ClassGrades], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listClasses' : IDL.Func([], [IDL.Vec(ClassInfo)], ['query']),
    'listStudents' : IDL.Func([IDL.Nat], [IDL.Vec(StudentInfo)], ['query']),
    'removeStudent' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveAttendance' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };